### ISSUE TITLE
主包可以使用unity开发吗?如果可以怎么接入试玩包呢?我知道试玩包只能使用cocos和laya开发

### ISSUE THREAD

**Issue by FourTest** [wechat-miniprogram/minigame-playable#7]
主包可以使用unity开发吗?如果可以怎么接入试玩包呢?我知道试玩包只能使用cocos和laya开发

**Comment by yuanzm** [comment]
不可以，文档有明确说。

**Comment by FourTest** [comment]
文档只是说试玩包不能使用unity开发吧
我现在游戏试unity开发的，试玩包使用cocos不行吗？

**Comment by FourTest** [comment]
> 不可以，文档有明确说。

Q5. 为什么Unity小游戏不能够用Unity开发试玩包？ Unity制作的试玩包强依赖引擎插件能力，目前暂不支持；建议开发者使用Cocos/Laya进行试玩分包开发。

看这好像是说试玩包不能使用unity开发吧。没说主包使用Unity开发的游戏不能开发试玩包
